### DISCUSSION TITLE
Does anyone have an example nginx reverse proxy config file for the docker compose setup?

### DISCUSSION THREAD

**Discussion by adambirds** [featbit/featbit#586] [Q&A]
Does anyone have an example nginx reverse proxy config file for the docker compose setup?

I'm just not quite sure how to put it all together with the multiple servers.

**Comment by deleteLater** [comment]
How about using this one: [nginx-gateway.conf](https://github.com/featbit/featbit/blob/main/modules/front-end/nginx-gateway.conf)

1. Clone repo: `git clone https://github.com/featbit/featbit && cd featbit`
2. Copy and paste the following content into `docker-compose.yml`

```yml
name: featbit
version: "3"
services:

  gateway:
    image: nginx:latest
    restart: always
    volumes:
      - ./modules/front-end/nginx-gateway.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - featbit-network

  ui:
    image: featbit/featbit-ui:latest
    restart: always
    environment:
      - API_URL=
      - DEMO_URL=https://featbit-samples.vercel.app
      - EVALUATION_URL=
    depends_on:
      - api-server
    ports:
      - "8081:80"
    networks:
      - featbit-network

  api-server:
    image: featbit/featbit-api-server:latest
    restart: always
    environment:
      - MongoDb__ConnectionString=mongodb://admin:password@mongodb:27017
      - MongoDb__Database=featbit
      - Redis__ConnectionString=redis:6379
      - OLAP__ServiceHost=http://da-server
    depends_on:
      - mongodb
      - redis
      - da-server
    ports:
      - "5000:5000"
    networks:
      - featbit-network

  evaluation-server:
    image: featbit/featbit-evaluation-server:latest
    restart: always
    environment:
      - MongoDb__ConnectionString=mongodb://admin:password@mongodb:27017
      - MongoDb__Database=featbit
      - Redis__ConnectionString=redis:6379
    depends_on:
      - mongodb
      - redis
    ports:
      - "5100:5100"
    networks:
      - featbit-network

  da-server:
    image: featbit/featbit-data-analytics-server:latest
    restart: always
    depends_on:
      - mongodb
      - redis
    ports:
      - "8200:80"
    networks:
      - featbit-network
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: mongodb://admin:password@mongodb:27017
      MONGO_INITDB_DATABASE: featbit
      MONGO_HOST: mongodb

  mongodb:
    image: mongo:5.0.14
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=featbit
    volumes:
      - mongodb:/data/db
      - ./infra/mongodb/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - featbit-network

  redis:
    image: bitnami/redis:6.2.10
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - featbit-network
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

networks:
  featbit-network:
    name: featbit-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16

volumes:
  mongodb:
  redis:
```

> [!TIP]
> Compared to the original docker-compose.yml, wo do the following change
> - Add gateway service
> - Unset API_URL and EVALUATION_URL for ui service

3. Run services: `docker compose up -d`
